### ISSUE TITLE
Ability to Invoke SML REPL from Vim

### ISSUE THREAD

**Issue by lemorage** [chilicuil/vim-sml-coursera#11]
Does the plugin let us fire up the SML REPL right from inside Vim, similar to how it's done in Emacs? Couldn't spot that info in the docs. Thanks!

**Comment by javier-lopez** [comment]
Hello @lemorage , 

I'm not sure how it works in Emacs, however this plugin is quite simple, it only adds syntax colour and binds the `:make` command to the sml interpreter so it executes what is in the buffer, there exists an option `let sml_interactive=1` that allows to stay in sml instead of getting back instantly to vim but that is all the interactivity it provides 😞

**Comment by lemorage** [comment]
@javier-lopez Gotcha. Thanks for clearing that up! 👍😊
